### ISSUE TITLE
Generate index.html info page when FS has been wiped

### ISSUE THREAD

**Issue by luismoser99** [NewTec-GmbH/ZumoComSystem#57]
Generate an index.html file which can be accessed even after the file system and the entire webspace has been wiped, so that the user knows that the webspace is empty but the server is not malfunctioning

**Comment by BlueAndi** [comment]
How does the system starts up, with a filesystem, which can not be mounted? :-)
Can the normal user really delete the whole filesystem?
Isn't that just a use case in theory?

**Comment by luismoser99** [comment]
> 
> 
> How does the system starts up, with a filesystem, which can not be mounted? :-)
> Can the normal user really delete the whole filesystem?
> Isn't that just a use case in theory?

The FS partition needs to be existent but it is not required that the partition comes pre-formatted with SPIFFS. If the FS cannot be mounted, it will automatically be formatted with SPIFFS.
Currently the FS only holds the webspace and the firmware image for the Zumo robot, so that the system can boot without any working FS.

No, currently the user cannot wipe the FS. It is planned to provide a reset service which can be invoked by hardware buttons which deletes all preferences and firmware images but does not touch any of the webspace content.

The idea behind this enhancement is, that if someone forgets to upload the webspace/FS image, the user can still access the webserver and be notified that there are no files to serve available

**Comment by BlueAndi** [comment]
There must be a lot of things go wrong, that this happens. If you build with VSCode ... the FS is automatically created with the right files. Autom. formatting might be not a good idea, because the error already happened before. At the end, the info is just for the developer, not the user.

Proposal: Disable autom. formatting, this is dangerous. If filesystem is corrupt, halt and provide error information via serial.
