### ISSUE TITLE
Fix FirmwareInfo database bug

### ISSUE THREAD

**Issue by luismoser99** [NewTec-GmbH/ZumoComSystem#84]
Uploading and flashing multiple firmware files for ZUMO or COM without reboothing the ComPlatform causes the FirmwareInfo databasae to throw a "database is full" error even though this is not the case

**Comment by gabryelreyes** [comment]
Bug is reproduced by trying to upload more than one firmware to the ComPlatform during the same session (without rebooting the ESP).
After this, there is no saved firmware available in the database
[Bug_Reproduction.txt](https://github.com/NewTec-GmbH/ZumoComSystem/files/8390389/Bug_Reproduction.txt)

**Comment by gabryelreyes** [comment]
Possible cause : m_savedFirmwares gets set to 3 even though the max number of firmwares allowed is 2.
`[D]	              FirmwareInfo.cpp:109	Number of saved Firmwares: 3`
However this limit is checked before a firmware is saved (FirmwareInfo.cpp:73). Must check if FirmwareInfo.cpp:241 can cause the problem

**Comment by gabryelreyes** [comment]
`m_savedFirmwares` is increased by 1 every time a firmware is flashed onto the Zumo.
Steps to reproduce the error:

1. Upload a firmware throught the Web Interface
2. Flash the firmware to the Zumo
3. Observe Logs for `[D] FirmwareInfo.cpp:109 Number of saved Firmwares: #`
4. Flash firmware again WITHOUT uploading a new one
5. Observe Logs for `[D] FirmwareInfo.cpp:109 Number of saved Firmwares: # + 1`
6. Repeat steps 4 and 5. Number of Firmwares increases even though there is no new firmware uploaded

**Comment by gabryelreyes** [comment]
Increment of variable caused by:
|-`bool Store::loadFirmwareInfo()`  in [FlashZumoCommand.cpp:80](https://github.com/NewTec-GmbH/ZumoComSystem/blob/c22d5b6a376b434f9727ca286af4cf205fe8d0ee/Coding/server/lib/API/FlashZumoCommand.cpp#L80) and [FlashZumoCommand.cpp:69](https://github.com/NewTec-GmbH/ZumoComSystem/blob/c22d5b6a376b434f9727ca286af4cf205fe8d0ee/Coding/server/lib/API/FlashZumoCommand.cpp#L69)
|--> `bool FirmwareInfo::deserialize(const String& serial)`  in [Store.cpp:281](https://github.com/NewTec-GmbH/ZumoComSystem/blob/c22d5b6a376b434f9727ca286af4cf205fe8d0ee/Coding/server/lib/Data/Store.cpp#L281)
|----> `m_savedFirmwares++;`  in [FirmwareInfo.cpp:241](https://github.com/NewTec-GmbH/ZumoComSystem/blob/c22d5b6a376b434f9727ca286af4cf205fe8d0ee/Coding/server/lib/Data/FirmwareInfo.cpp#L241)
