### ISSUE TITLE
Fix watchdog timeout on firmware upload

### ISSUE THREAD

**Issue by luismoser99** [NewTec-GmbH/ZumoComSystem#85]
Sometimes when a firmware is uploaded, a system watchdog timeout occurs

**Comment by gabryelreyes** [comment]
Timeout of HTTPS Server caused by the long time required to flash and verify of the firmware of the Zumo.

**Comment by BlueAndi** [comment]
Is the verification process done in the same webserver request context?

**Comment by gabryelreyes** [comment]
Yes, the whole process of flashing and verifying is triggered by the webserver, and blocks its further handling until its finished (See [here](https://github.com/NewTec-GmbH/ZumoComSystem/blob/8c296e2cf8ac404986fd13cb705c743080fa10b2/Coding/server/lib/API/FlashZumoCommand.cpp#L62))

**Comment by gabryelreyes** [comment]
Even just flashing (without verifying) a large firmware (20 kB) takes long enough to timeout the connection

**Comment by gabryelreyes** [comment]
Just tested: The connection does not time-out if the client sends requests during the flashing process, for example, changing to the upload window of the web interface. This requests the firmware info, and keeps the connection alive.

**Comment by BlueAndi** [comment]
> Just tested: The connection does not time-out if the client sends requests during the flashing process, for example, changing to the upload window of the web interface. This requests the firmware info, and keeps the connection alive.

Hmm ... but thats different. Is the root cause that the connection gets closed or because the webserver request context is blocked too long?

**Comment by gabryelreyes** [comment]
I am not sure yet. The client only loses connection to the server/ closes the websocket when the server is finished flashing the Zumo. 
In other words, once the server is able to handle the connection again, it closes it because of the timeout.

But for that reason I find strange that by sending requests, the connection does not time out. The requests are still handled (get the firmware info) after the flashing is done.

**Comment by BlueAndi** [comment]
I think I see the problem. All websocket commands are handled in one single call. The websocket connection will run into a timeout and closes the connection. Better would be to queue the commands and handle them in the main context. Have a look to the sequence diagram, which shows the handling. This will help.

**Comment by gabryelreyes** [comment]
I understand what you mean, but even being in the main context, wouldn't it still timeout if the flashing process takes too long?

**Comment by BlueAndi** [comment]
IMHO the main context task watchdog is disabled.
Anyway there you can handle it in several steps, without doing it in one single call.
The websocket connection is kept open by the webserver.

**Comment by gabryelreyes** [comment]
Alright, so i propose getting all the information of the request, and instead of making the call to the API, it stores the response in a queue. This would be done in  [Session.cpp:167](https://github.com/NewTec-GmbH/ZumoComSystem/blob/8c296e2cf8ac404986fd13cb705c743080fa10b2/Coding/server/lib/Data/Session.cpp#L167).

The question is, if we should push the whole request data into the queue, or put it in a variable and push a pointer to it ([FreeRTOS Queue](https://www.freertos.org/a00117.html)). Obviously depends on the size of the request, but I believe the max. size of the Websocket Buffer is set to 2048 Bytes.
